# -*- coding: utf-8 -*-
"""shahina reserve words.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ApfOhbEaQwylrdzUXrNzdn4G766JyBAB
"""

# Create a list of words
word_list = ["Hello", "world", "Python", "is", "fun"]

# Reverse the order of the words in the list
reversed_list = word_list[::-1]

# Display the reversed list
print("Original list of words:", word_list)
print("Reversed list of words:", reversed_list)

